// <auto-generated />
using IdentityMatchingWebsite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdentityMatchingWebsite.Migrations
{
    [DbContext(typeof(IdentityMatchingWebsiteContext))]
    partial class IdentityMatchingWebsiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityMatchingWebsite.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<string>("LegalSurname");

                    b.Property<string>("Surname");

                    b.HasKey("ID");

                    b.ToTable("Person");

                    b.HasData(
                        new { ID = 1, DateOfBirth = "13/03/1997", FirstName = "Steve", LegalSurname = "Smith", Surname = "Smith" },
                        new { ID = 2, DateOfBirth = "29/02/2000", FirstName = "James", LegalSurname = "Franks", Surname = "Franks" },
                        new { ID = 3, DateOfBirth = "23/11/1980", FirstName = "Eric", LegalSurname = "Harden", Surname = "Harden" },
                        new { ID = 4, DateOfBirth = "23/11/1980", FirstName = "James", LegalSurname = "Samson", Surname = "Samson" },
                        new { ID = 5, DateOfBirth = "16/08/1977", FirstName = "Guy", LegalSurname = "Hammer", Surname = "Hammer" },
                        new { ID = 6, DateOfBirth = "13/03/1997", FirstName = "Sam", LegalSurname = "Swanson", Surname = "Swanson" },
                        new { ID = 7, DateOfBirth = "6/08/1977", FirstName = "Sarah", LegalSurname = "Smith", Surname = "Morgan" },
                        new { ID = 8, DateOfBirth = "13/03/1966", FirstName = "Hugh", LegalSurname = "Mungus", Surname = "Mungus" }
                    );
                });

            modelBuilder.Entity("IdentityMatchingWebsite.Models.PersonTwo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<string>("LegalSurname");

                    b.Property<string>("Surname");

                    b.HasKey("ID");

                    b.ToTable("PersonTwo");

                    b.HasData(
                        new { ID = 1, DateOfBirth = "13/03/1997", FirstName = "Steve", LegalSurname = "Smith", Surname = "Smith" },
                        new { ID = 2, DateOfBirth = "	29/02/2000", FirstName = "Sam", LegalSurname = "Hammer", Surname = "Hammer" },
                        new { ID = 3, DateOfBirth = "23/11/1989", FirstName = "Joe", LegalSurname = "Swanson", Surname = "Swanson" },
                        new { ID = 4, DateOfBirth = "23/11/1980", FirstName = "Eric", LegalSurname = "Jones", Surname = "Jones" },
                        new { ID = 5, DateOfBirth = "16/08/1977", FirstName = "Emily", LegalSurname = "Smith", Surname = "Smith" },
                        new { ID = 6, DateOfBirth = "13/03/1997", FirstName = "Steve", LegalSurname = "Swanson", Surname = "Swanson" },
                        new { ID = 7, DateOfBirth = "23/11/1970", FirstName = "Rebecca", LegalSurname = "Mungus", Surname = "Ferguson" },
                        new { ID = 8, DateOfBirth = "16/08/1962", FirstName = "Sarah", LegalSurname = "Franks", Surname = "Harris" }
                    );
                });

            modelBuilder.Entity("IdentityMatchingWebsite.Models.Results", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<string>("LegalSurname");

                    b.Property<string>("Surname");

                    b.HasKey("ID");

                    b.ToTable("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
